model_list:
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: openai/z-ai/glm-5.2
      api_base: https://apiai-production.up.railway.app/v1
      api_key: sk-8e36745890783d0e97258cbfbf9f346dd1b248935dffcc36
      timeout: 600
      stream_timeout: 120
  - model_name: claude-3-7-sonnet-20250219
    litellm_params:
      model: openai/z-ai/glm-5.2
      api_base: https://apiai-production.up.railway.app/v1
      api_key: sk-8e36745890783d0e97258cbfbf9f346dd1b248935dffcc36
      timeout: 600
      stream_timeout: 120
